version: '3'
services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
      # Only using RAM
      #- ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - db