# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# This file is checked in to a public repository
# therefore don't store real secrets in here directly
# instead read them from the environment.

common: &common
  joshua_project_api_key: <%= ENV["JOSHUA_PROJECT_API_KEY"] %>
  sms_api_key: <%= ENV["SMS_API_KEY"] %>
  sms_api_token: <%= ENV["SMS_API_TOKEN"] %>
  bcs_encrypt_key: <%= ENV["BCS_ENCRYPT_KEY"] %>
  bcs_encrypt_algorithm: AES-128-ECB
  sms_key: <%= ENV["SMS_KEY"] %>

development:
  <<: *common
  secret_key_base: 656e795472d23a239d5dd61552fb14978e018fb67eb49783f6820a7a2d51ce3fb92c86b48f35a97ffdf1bab1383081875ef52fab85fb0c899ec3d5832068bfd8
  recaptcha_site_key: '6LdiuWwUAAAAAG75LDNo_qvFiemkDWHtz1T7C-rI'
  recaptcha_secret_key: '6LdiuWwUAAAAAHQ2NH_DsdKoY0-JPqtw8MUo3B0I'

test:
  <<: *common
  secret_key_base: f6431a40bfee7d9cb250b24b30051f771f160f5b85c692729282775dcdc49410ab99d8c88c15674458053f1618b4676e8b9195794d8d10f306c3c975bb521154
  recaptcha_site_key: '6LdiuWwUAAAAAG75LDNo_qvFiemkDWHtz1T7C-rI'
  recaptcha_secret_key: '6LdiuWwUAAAAAHQ2NH_DsdKoY0-JPqtw8MUo3B0I'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
